apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add the namespace to the resources
namespace: demo-multi-node-multi-gpu

resources:
  - dsp.yaml # Data Science Project / Namespace
  - model-pvc.yaml # PVC for model storage
  - token.yaml # HuggingFace Token
  - download-model-to-pvc.yaml # Download model to PVC
