---
apiVersion: v1
kind: Namespace
metadata:
  name: nfsprovisioner-operator
---  
apiVersion: cache.jhouse.com/v1alpha1
kind: NFSProvisioner
metadata:
  name: nfsprovisioner-sample
  namespace: nfsprovisioner-operator
spec:
  scForNFS: nfs
  scForNFSPvc: gp3-csi
  storageSize: 100Gi