apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add the namespace to the resources
namespace: demo-multi-node-multi-gpu

# These are the Operators required to install the RHOAI + KServe + Authorino Stack
resources:
  - vllm-multinode-sr.yaml # VLLM Multi-Node ServingRuntime
  - custom-crd.yaml # Update ServingRuntime and InferenceService CRD